const $=id=>document.getElementById(id);
const eye='<svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></svg>';
let activeLab=null,activeReport=null,leftMode='labs',rightMode='reports',labScroll=0,reportScroll=0;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=s=>s.slice(5,7)+'/'+s.slice(8,10)+'/'+s.slice(0,4)+' '+s.slice(11,16);
const matchesYear=(d,y)=>y==='all'||d.startsWith(y);
const labGroups=['Misc','Chemistries','Serum','Blood Gas','Serum Other','CBC','Anemia Labs','Vitamins','Cardiac Markers','Endocrine Studies','ID Studies','CSF Studies','LFTs','Pancreatic Enzymes','Proteins','Inflammatory Markers','Tumor Markers','UA Analysis','Autoimmune Studies'];
const expandedLabGroups=new Set();
const source=(page,label='View source PDF',pdf='demo')=>`<button class="source" data-page="${page}" data-pdf="${pdf}">${eye} ${label} · p. ${page}</button>`;
function renderLabs(){leftMode='labs';$('leftTitle').textContent='Labs';$('backLabs').hidden=true;$('labYear').hidden=false;$('labSearchBox').hidden=false;
const q=$('labSearch').value.toLowerCase(),y=$('labYear').value;let html='<div class="colheads"><span>TEST</span><span>LATEST VALUE</span><span>COLLECTED</span></div>',count=0;
const rowHtml=l=>{const key=l.id||l.name,v=l.values.find(v=>matchesYear(v.date,y));
if(!v){if(!l.id)return '';return `<button class="labrow ${activeLab===key?'selected':''}" data-lab="${esc(key)}" aria-label="View ${esc(l.full)} history"><strong>${esc(l.name)}</strong><span class="noresult">No results available</span><time>—</time></button>`;}
const abnormal=v.value<l.low||v.value>l.high;return `<button class="labrow ${activeLab===key?'selected':''}" data-lab="${esc(key)}" aria-label="View ${esc(l.full)} history"><strong>${esc(l.name)}</strong><span>${abnormal?'<mark>':''}${esc(v.value)}${abnormal?'</mark><span class="flag">'+(v.value>l.high?'H':'L')+'</span>':''}</span><time>${date(v.date)}</time></button>`;};
for(const group of labGroups){
const matching=LABS.filter(l=>l.group.toLowerCase()===group.toLowerCase()&&(l.name+' '+l.full+' '+group+' '+(l.subgroup||'')).toLowerCase().includes(q));
let rows=matching.filter(l=>!l.subgroup).map(rowHtml).join('');
for(const subgroup of group==='CBC'?['Diff']:group==='Blood Gas'?['ABG','VBG']:[]){const subrows=matching.filter(l=>l.subgroup===subgroup).map(rowHtml).join('');if(subrows||!q)rows+=`<details class="lab-subgroup" data-group="${group}:${subgroup}" ${expandedLabGroups.has(group+':'+subgroup)||q?'open':''}><summary>${subgroup}</summary>${subrows||'<div class="empty">No results available in this category for the selected date range.</div>'}</details>`;}
if(rows||!q||group.toLowerCase().includes(q))html+=`<details data-group="${group}" ${expandedLabGroups.has(group)||q?'open':''}><summary>${group}</summary>${rows||'<div class="empty">No results available in this category for the selected date range.</div>'}</details>`;
}
$('leftBody').innerHTML=html.includes('<details')?html:'<div class="empty">No matching laboratory results.</div>';
$('leftBody').querySelectorAll('details[data-group]').forEach(el=>el.addEventListener('toggle',()=>{if(el.open)expandedLabGroups.add(el.dataset.group);else expandedLabGroups.delete(el.dataset.group);}));}
function reportRows(reports){let last='';return reports.map(r=>{let year='';if(last!==r.date.slice(0,4)){last=r.date.slice(0,4);year=`<div class="year">${last}</div>`}return year+`<button class="report ${activeReport===r.id?'selected':''}" data-report="${r.id}"><div><strong>${esc(r.title)}</strong><small>${esc(r.subtitle)}</small></div><time>${date(r.date)}</time></button>`}).join('');}
function renderReports(){rightMode='reports';$('rightTitle').textContent='Reports';$('backReports').hidden=true;$('category').hidden=false;$('reportYear').hidden=false;$('reportSearchBox').hidden=false;
const q=$('reportSearch').value.toLowerCase(),cat=$('category').value,y=$('reportYear').value;
const filtered=REPORTS.filter(r=>matchesYear(r.date,y)&&(cat==='All'||cat===r.category)&&(r.title+' '+r.author+' '+r.sections.flat().join(' ')).toLowerCase().includes(q)).sort((a,b)=>b.date.localeCompare(a.date));
const main=filtered.filter(r=>r.category!=='Microbiology'),micro=filtered.filter(r=>r.category==='Microbiology');
$('rightBody').innerHTML=(main.length?reportRows(main):'')+(micro.length?'<div class="microhead">Microbiology</div>'+reportRows(micro):'')||'<div class="empty">No reports match these filters.</div>';}
function showHistory(name){if(rightMode==='reports')reportScroll=$('rightBody').scrollTop;activeLab=name;const l=LABS.find(x=>(x.id||x.name)===name);rightMode='history';$('rightTitle').textContent=l.name+' history';$('backReports').hidden=false;$('category').hidden=true;$('reportSearchBox').hidden=true;$('reportYear').hidden=false;
const values=l.values.filter(v=>matchesYear(v.date,$('reportYear').value));$('rightBody').innerHTML=`<div class="historyintro"><h3>${l.full}</h3><p>Collection time · Newest first · ${values.length} results</p></div><table class="history"><thead><tr><th>Collected</th><th>Value</th><th>Units</th><th>Reference</th><th>Source</th></tr></thead><tbody>${values.map(v=>`<tr><td>${date(v.date)}</td><td>${v.value<l.low||v.value>l.high?'<mark>'+v.value+'</mark>':v.value}</td><td>${l.unit}</td><td>${l.low}–${l.high}</td><td><button class="eye" data-page="${v.page}" data-pdf="${l.pdf||'demo'}" title="View source PDF, page ${v.page}" aria-label="Source for ${l.name} ${v.value} on ${date(v.date)}, page ${v.page}">${eye}</button></td></tr>`).join('')}</tbody></table>${values.length?'':'<div class="empty">No results in this date range.</div>'}`;$('rightBody').scrollTop=0;if(leftMode==='labs'){const pos=$('leftBody').scrollTop;renderLabs();$('leftBody').scrollTop=pos;}}
function showReport(id){if(leftMode==='labs')labScroll=$('leftBody').scrollTop;activeReport=id;leftMode='detail';const r=REPORTS.find(x=>x.id===id);$('leftTitle').textContent='Report detail';$('backLabs').hidden=false;$('labSearchBox').hidden=true;$('labYear').hidden=true;$('leftBody').innerHTML=`<article class="detail"><h3>${esc(r.title)}</h3><div class="meta">${date(r.date)} · ${esc(r.author)}<br>Alex Morgan · DEMO-001 · Synthetic source text</div>${source(r.page,'View source packet',r.pdf||'demo')}${['neuro','initial','ed'].includes(r.id)?`<button data-structured="${esc(r.id)}">Open in note template</button>`:''}${r.sections.map(([h,b])=>`<h4>${esc(h)}</h4><p>${esc(b)}</p>`).join('')}</article>`;$('leftBody').scrollTop=0;const pos=$('rightBody').scrollTop;renderReports();$('rightBody').scrollTop=pos;}
function openPdf(page,pdf='demo'){$('pdfTitle').textContent='Fictional source · Page '+page;$('pdfSub').textContent='synthetic-records.pdf · fictional demonstration packet';const url='synthetic-records.pdf#page='+page+'&view=FitH';$('pdfFrame').src=url;$('pdfExternal').href=url;$('pdfDialog').showModal();}
const cats=['All','CardioPulmonary','Clinical Notes','CT, MRI, & PET','Legal','Nuclear Medicine','Pathology','RX Report','Scanned Reports','Surgery & Procedure','Ultrasound','X-ray & Mammo','Unclassified'];$('category').innerHTML=cats.map(c=>`<option>${c}</option>`).join('');
document.addEventListener('click',e=>{const lab=e.target.closest('[data-lab]'),report=e.target.closest('[data-report]'),pdf=e.target.closest('[data-page]');if(lab)showHistory(lab.dataset.lab);if(report)showReport(report.dataset.report);if(pdf)openPdf(Number(pdf.dataset.page),pdf.dataset.pdf||'demo');});
$('labSearch').addEventListener('input',renderLabs);$('labYear').addEventListener('change',renderLabs);$('reportSearch').addEventListener('input',renderReports);$('category').addEventListener('change',renderReports);$('reportYear').addEventListener('change',()=>rightMode==='history'?showHistory(activeLab):renderReports());
$('backLabs').onclick=()=>{renderLabs();$('leftBody').scrollTop=labScroll;};$('backReports').onclick=()=>{renderReports();$('rightBody').scrollTop=reportScroll;};$('closePdf').onclick=()=>$('pdfDialog').close();$('pdfDialog').addEventListener('click',e=>{if(e.target===$('pdfDialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
$('reset').onclick=()=>{activeLab=null;activeReport=null;labScroll=reportScroll=0;$('labSearch').value=$('reportSearch').value='';$('labYear').value=$('reportYear').value='all';$('category').value='All';renderLabs();renderReports();$('leftBody').scrollTop=$('rightBody').scrollTop=0;};renderLabs();renderReports();

document.addEventListener('click',e=>{const b=e.target.closest('[data-structured]');if(b)openStructuredReport(REPORTS.find(r=>r.id===b.dataset.structured));});
