const assert=require('node:assert/strict');
const T=require('./note-templates.js'),E=require('./note-engine.js');
assert.equal(T.length,9);assert.equal(new Set(T.map(t=>t.id)).size,9);
for(const t of T){const ids=t.sections.flatMap(g=>g.fields.map(f=>f.id));assert.equal(ids.length,new Set(ids).size,t.id+' duplicate fields');assert.equal(E.validate(E.blank(t.id)).templateId,t.id);assert.equal(E.contract(t.id).sections,t.sections);}
let n=E.extract('consultation','[[PAGE 10]]\nDate: 11/27/2025\nAuthor: Resident Test, MD\nHPI:\nPatient denies weakness.\n[[PAGE 11]]\nSymptoms started yesterday.\nPhysical examination:\nNeurologic: Strength 4/5 left arm.\nAttending addendum:\nAuthor: Attending Test, MD\nSignature/time: 11/28/2025 08:00\nAssessment: Different impression.');
assert.equal(n.fields.hpi_0.length,2);assert.equal(n.fields.hpi_0[1].page,11);assert.equal(n.authors.length,1);assert.equal(n.addenda.length,1);assert.equal(n.addenda[0].author,'Attending Test, MD');assert.equal(n.addenda[0].signedAt,'11/28/2025 08:00');assert.ok(n.addenda[0].entries.some(e=>e.text.includes('Different impression')));assert.equal(n.fields.exam_8[0].text,'Strength 4/5 left arm.');assert.equal(n.fields.assessment_0,undefined);E.validate(n);
n=E.extract('hospital-progress','Medication changes / held / discontinued: Metoprolol held.\nUnrecognizedHeading: original content\nNext source line.');assert.equal(n.fields.meds_3[0].text,'Metoprolol held.');assert.equal(n.unmapped.length,2);assert.ok(!JSON.stringify(n).includes('otherwise negative'));
n=E.extract('office-progress','Assessment and plan:\n1. Problem; monitor.\n2. Follow up.');assert.equal(n.fields.plan_0.length,2);assert.equal(n.fields.assessment_0,undefined);
n=E.extract('icu-daily','Vitals: BP 90/50 at 08:00\nVBG: drawn 07:00\nABG: drawn 08:00\nCritical care time: 35 minutes excluding procedures');assert.equal(n.fields.data_6[0].text,'drawn 07:00');assert.equal(n.fields.data_5[0].text,'drawn 08:00');assert.equal(n.fields.critical_0[0].text,'35 minutes excluding procedures');
n=E.extract('slp','Current diet / IDDSI: puree\nRecommended diet / IDDSI: pending\nSigns of aspiration/penetration observed: cough at bedside');assert.equal(n.fields.swallow_1[0].text,'puree');assert.equal(n.fields.swallow_3[0].text,'pending');assert.equal(n.fields.swallow_9[0].text,'cough at bedside');
assert.throws(()=>E.extract('ed','[[PAGE 0]]'));assert.throws(()=>E.validate({...E.blank('ed'),fields:{bad:[]}}));assert.throws(()=>E.validate({...E.blank('ed'),fields:{ed_0:[{text:'a',originalText:'a',page:-1,line:1,status:'reviewed'}]}}));
console.log('PASS: all nine schemas, multi-page continuation, author/addendum separation, missing data, unmatched text, combined plan, ABG/VBG, diet context, import validation.');
